[platformio]
default_envs = sonoff_4chr3

[env:sonoff_4chr3]
platform = espressif8266@4.2.1
board = esp01_1m
framework = arduino
board_build.mcu = esp8266
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.f_flash = 40000000L
board_build.ldscript = eagle.flash.1m64.ld
monitor_speed = 9600
upload_speed = 115200
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -D VTABLES_IN_FLASH

[env:native]
platform = native
test_build_src = true
build_src_filter = +<protocol.cpp>
