import http from "node:http";
import fs from "node:fs";

const source=fs.readFileSync(new URL("../src/web_dashboard_page.h",import.meta.url),"utf8");
const themeSource=fs.readFileSync(new URL("../src/web_theme.h",import.meta.url),"utf8");
const theme=themeSource.match(/R"CSS\(([\s\S]*?)\)CSS"/)[1];
const page=source.match(/R"HTML\(([\s\S]*?)\)HTML"/)[1].replace("</head>",theme+"</head>");
const logic={devices:[0,1,2,3].map((i)=>({enabled:i<3,name:["Router główny","AP biuro","Kamera magazyn","Kanał 4"][i],icon:[1,3,7,0][i],power_channel:i,pulse_seconds:10,stabilization_seconds:60,cooldown_seconds:300,maximum_recoveries_per_hour:3})),targets:[
 {enabled:true,name:"Router LAN",icon:1,address:"192.168.1.1",test:0},{enabled:true,name:"AP biuro",icon:3,address:"192.168.1.99",test:0},{enabled:true,name:"Internet A",icon:8,address:"1.1.1.1",test:0},{enabled:true,name:"Internet B",icon:8,address:"8.8.8.8",test:0},{enabled:true,name:"DNS MarkLabs",icon:9,address:"marklabs.pl",test:4},...Array.from({length:7},()=>({enabled:false,name:"",icon:0,address:"",test:0}))].map(x=>({...x,port:0,path:"/",expected_http_code:200,timeout_ms:1000})),rules:[{enabled:true,name:"Restart AP przy lokalnej awarii",operator:0,condition_count:3,consecutive_cycles:3,powered_device_index:1,conditions:[{target_index:1,expected_state:1},{target_index:0,expected_state:0},{target_index:2,expected_state:0},{target_index:0,expected_state:0}]},...Array.from({length:7},()=>({enabled:false,name:"",operator:0,condition_count:1,consecutive_cycles:3,powered_device_index:0,conditions:Array.from({length:4},()=>({target_index:0,expected_state:0}))}))]};
const engine={valid:true,running:false,completed_runs:184,requested:2,executed:2,failed:0,pulse_pending:false,pending_device:0,last_decision_at_ms:3710000,last_decision:"PULSE CONFIRMED DEVICE 2",targets:logic.targets.map((x,i)=>({enabled:x.enabled,ok:i!==1,response_ms:[1.2,0,8.4,11.2,24][i]||0,response_code:0,checks:x.enabled?184:0,successes:x.enabled?(i===1?181:184):0})),devices:logic.devices.map((x,i)=>({stabilization_remaining_seconds:i===1?24:0,cooldown_remaining_seconds:i===1?264:0,recoveries_in_current_hour:i===1?1:0})),rules:logic.rules.map((x,i)=>({enabled:x.enabled,matched:i===0,matching_cycles:i===0?2:0,required_cycles:x.consecutive_cycles,state:i===0?2:0})),events:[{timestamp_ms:3400000,message:"RULE 1 PULSE CH2"},{timestamp_ms:3401200,message:"PULSE CONFIRMED DEVICE 2"}]};
const status={product:"NETGUARD-MASTER",version:"0.8.0-alpha.3",mode:"PRODUCTION",system:{uptime_ms:3723000,free_heap:181456,min_free_heap:169320,automation_enabled:true,startup_delay_seconds:120,reset_reason:"POWER_ON"},ethernet:{link:true,has_ip:true,ip:"192.168.1.23",mac:"AA:BB:CC:DD:EE:FF",link_changes:1,speed_mbps:100,full_duplex:true},power_module:{online:true,last_response_ms:1240,heartbeats:744,consecutive_heartbeats:32,timeouts:0,invalid_lines:0,command_pending:false,last_status:"READY"}};
http.createServer((req,res)=>{res.setHeader("Content-Type",req.url==="/"?"text/html":"application/json");res.end(req.url==="/"?page:JSON.stringify(req.url.includes("logic/status")?engine:req.url.includes("logic")?logic:status));}).listen(8765,"127.0.0.1",()=>console.log("Dashboard preview: http://127.0.0.1:8765/"));
