#pragma once

#include <Arduino.h>

namespace web {
static const char kSharedTheme[] PROGMEM = R"CSS(<style>
:root{--bg:#06101d;--surface:#0b1b2d;--surface2:#10243a;--line:#21435f;--primary:#268cff;--accent:#14c8d4;--text:#f2f8fc;--muted:#91a9bb;--ok:#20c997;--warn:#f5b942;--bad:#ff6470;--shadow:0 18px 50px #0006}
*{box-sizing:border-box}html{color-scheme:dark;scroll-behavior:smooth}body{background:radial-gradient(900px 480px at 8% -10%,#173d62 0,transparent 65%),radial-gradient(700px 380px at 100% 0,#08394a 0,transparent 62%),var(--bg)!important;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif!important;letter-spacing:.005em}
.wrap,.w{width:min(1180px,100%);margin-inline:auto;padding:24px!important}.top{min-height:48px;display:flex;align-items:center!important;gap:16px}.brand{font-size:20px!important;letter-spacing:-.02em}.brand span{color:var(--primary)!important}.brandDomain{color:var(--accent);font-size:.62em;font-weight:800;letter-spacing:.04em;margin-left:1px;vertical-align:.18em}
.nav,.tabs{display:flex!important;align-items:center;gap:6px!important;overflow-x:auto;background:#071523d9!important;border:1px solid var(--line)!important;border-radius:16px!important;padding:6px!important;margin:20px 0 30px!important;box-shadow:0 10px 28px #0003;scrollbar-width:none}.nav::-webkit-scrollbar,.tabs::-webkit-scrollbar{display:none}.nav a,.tabs a{flex:0 0 auto;color:var(--muted)!important;text-decoration:none;padding:10px 15px!important;border-radius:11px!important;font-weight:650;font-size:14px;transition:.18s ease}.nav a:hover,.tabs a:hover{background:#17314a;color:var(--text)!important}.nav .active,.tabs .active{background:linear-gradient(135deg,#1976e8,var(--primary))!important;color:white!important;box-shadow:0 7px 18px #1877dc55}
h1{font-size:clamp(29px,4vw,43px);line-height:1.08;letter-spacing:-.035em;margin:0 0 10px}h2{letter-spacing:-.025em}h3{letter-spacing:-.015em}.lead{font-size:16px;line-height:1.65;max-width:760px}.card,.section{background:linear-gradient(145deg,#10243ae8,#091827ee)!important;border:1px solid var(--line)!important;border-radius:18px!important;box-shadow:var(--shadow)}.card{transition:transform .18s ease,border-color .18s ease}.card:hover{transform:translateY(-2px);border-color:#32658a!important}
button,.action,.save,.upload{min-height:42px;border-radius:11px!important;font:inherit;font-weight:750!important;cursor:pointer;transition:transform .15s ease,filter .15s ease,opacity .15s ease}button:hover:not(:disabled),.action:hover:not(:disabled),.save:hover:not(:disabled){filter:brightness(1.12);transform:translateY(-1px)}button:disabled{cursor:not-allowed;opacity:.52}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #28a5ff55;outline-offset:2px}
input,select,textarea{min-height:43px;background:#061421!important;color:var(--text)!important;border:1px solid #2a526e!important;border-radius:11px!important;padding:10px 12px!important;font:inherit}input:hover,select:hover,textarea:hover{border-color:#3c7398!important}input:focus,select:focus,textarea:focus{border-color:var(--primary)!important;box-shadow:0 0 0 3px #268cff22}.badge{border:1px solid currentColor!important;font-weight:800!important;letter-spacing:.045em}.muted,.help,.lead,.label,.role{color:var(--muted)!important}.ok{color:var(--ok)!important}.warn{color:var(--warn)!important}.bad{color:var(--bad)!important}
@media(max-width:720px){.wrap,.w{padding:15px!important}.top{align-items:flex-start!important}.nav,.tabs{margin:14px 0 23px!important;border-radius:13px!important}.nav a,.tabs a{padding:9px 12px!important}.grid,.summary{grid-template-columns:1fr!important;flex-direction:column}.card,.section{border-radius:15px!important}h1{font-size:30px}}
</style>)CSS";
}
